### ISSUE TITLE
Error in commands which I am trying to run

### ISSUE THREAD

**Issue by manohar8** [jcapelladesto/geoRge#10]
Hi, 
I could run script for geoRge with partial success for sample data (mtbls213). This is what I am trying
->library(xcms)

>library(geoRge)

>data(mtbls213)

>sampclass(mtbls213) <- c(rep("CELL_Glc12_05mM_Normo", 3), rep("CELL_Glc13_05mM_Normo", 3),rep("CELL_Glc13_25mM_Normo", 3), rep("CELL_Glc13_25mM_Normo", 3))

>s1 <- PuInc_seeker(XCMSet=mtbls213,ULtag="CELL_Glc12",Ltag="CELL_Glc13",sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 4000)

>s2 <- basepeak_finder(PuIncR = s1, XCMSet = mtbls213, UL.atomM=12.0,L.atomM=13.003355,ppm.s=6.5,Basepeak.minInt=2000)

>s4 <- label_compare(geoRgeR = s2, XCMSet = mtbls213, ppm.s = 6.5,rt.win.min = 1, control.cond = "05mM_Normo", fc.vs.Control = 1, p.value.vs.Control = 0.05, Show.bp = T)

>str (s4)

>s5 <- database_query(geoRgeR = s2, adducts = M-H, db = "C:/Users/Admin/Downloads/Compressed/geoRge-master/inst/extdata/ExampleDatabase.csv", ppm.db = 10)

1. I do not see comparison between 5 and 25 mM conditions in label compare file i.e, s4. Please suggest.
2. s4 table only has Base peak, X05mM_Normo_MEAN and X05mM_Normo_SD. 
mzmed and rtmed columns are missing.
2. I am not able to run database query command (s5) which I think generates the file (Supplementary table 1- ac5b03628_si_001 from the manuscript). The problem is - 
Error in DatabaseSearch(input, db, ppm.db, adducts) : 
  object 'M' not found
3. Do we also get putative id's for labeled features from the given HMDB database like they are shown in ac5b03628_si_001

I am newbie in this type of analysis. It would be of immense help to me if code given here is rectified.
Thanks a lot.

**Comment by jcapelladesto** [comment]
Hi manohar8,

I see you got some mixed lines of code. Do not worry, let me show you what you should run:
`library(geoRge)`
`data(mtbls213)`

Ignore this:
> sampclass(mtbls213) <- c(rep("CELL_Glc12_05mM_Normo", 3), rep("CELL_Glc13_05mM_Normo", 3),rep("CELL_Glc13_25mM_Normo", 3), rep("CELL_Glc13_25mM_Normo", 3))

First analysis step, look for candidate features that could be labelled:
`s1 <- PuInc_seeker(XCMSet=mtbls213,ULtag="CELL_Glc12",Ltag="CELL_Glc13",sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 4000)`

Second analysis step, of those find in first step, try to find if they have an unlabelled peak that can be associated to them (the nonlabelled feature):
`s2 <- basepeak_finder(PuIncR = s1, XCMSet = mtbls213, UL.atomM=12.0,L.atomM=13.003355,ppm.s=6.5,Basepeak.minInt=2000)`

This is optional, if you have many experimental conditions, you then could compare if any condition is significantly more labelled than a control condition:
```
s3 <- label_compare(geoRgeR = s2, XCMSet =mtbls213, rt.win.min = 1, 
										control.cond = "05mM_Normo",ppm.s=6.5,
										fc.vs.Control = 1, p.value.vs.Control = 0.05, Show.bp = T)
```

Searching in the database. The package includes files for searching hits for the labelled features reported in the data.frame. 

In this case, we load the negative adducts in a data.frame
```
negative <- read.table(system.file("extdata/adducts_negative.txt", package="geoRge"),
                       header=T,stringsAsFactors=F)
```
Then, the database.
```
db <- read.csv(system.file("extdata/ExampleDatabase.csv", package="geoRge"),
                header=T,stringsAsFactors=F,fill=T)
```
Then the -database_query- function we use both datasets to report look for hits for the results of the second analysis (s2).
`hits <- database_query(geoRgeR = s2, adducts = negative, db = db)`

I hope this very short summary helps you. If you have any other question regarding the workflow or you encounter any problem running your data, just post in this issue again.

**Comment by manohar8** [comment]
Thank you very much for a quick response.  The overall flow of the script is now clear. 
However a small error occurs for the last command
hits <- database_query(geoRgeR = s2, adducts = negative, db = db)
Error in which(as.numeric(db$Monoisotopic.Mass) >= mass_range[1] & as.numeric(db$Monoisotopic.Mass) <=  : 
  object 'db' not found

Please reply.
Manohar

**Comment by jcapelladesto** [comment]
Hi manohar,

Sorry for the delay. 
That is a weird error. Could you paste here the output of 

> head(db)

after loading the CSV file.

**Comment by manohar8** [comment]
Hi Jordi,
Your suggestion worked. Thank you very much. I just included one more line of code before hits command i.e 
> db<- read.csv(file="C:/Users/Admin/Documents/R/win-library/3.2/geoRge/extdata/ExampleDatabase.csv", header=TRUE, sep=",")
> head(db)
    HMDB.ID                      Name Chemical.Formula Monoisotopic.Mass
1 HMDB00001         1-Methylhistidine        C7H11N3O2          169.0851
2 HMDB00002        1,3-Diaminopropane          C3H10N2           74.0844
3 HMDB00005        2-Ketobutyric acid           C4H6O3          102.0317
4 HMDB00008     2-Hydroxybutyric acid           C4H8O3          104.0473
5 HMDB00010          2-Methoxyestrone         C19H24O3          300.1725
6 HMDB00011 (R)-3-Hydroxybutyric acid           C4H8O3          104.0473
The final command i.e. hits <- database_query(geoRgeR = s2, adducts = negative, db = db) now works fine.
I am now getting the tables for s3 and hits.However the information in these tables is incomplete However I would like to know how was the supplementary table in the manuscript was generated using using the sample data.

**Comment by manohar8** [comment]
Hi Jordi,
Sorry by mistake I closed this comment. Your suggestion worked. Thank you very much. I just included one more line of code before hits command i.e

db<- read.csv(file="C:/Users/Admin/Documents/R/win-library/3.2/geoRge/extdata/ExampleDatabase.csv", header=TRUE, sep=",")
head(db)
HMDB.ID Name Chemical.Formula Monoisotopic.Mass
1 HMDB00001 1-Methylhistidine C7H11N3O2 169.0851
2 HMDB00002 1,3-Diaminopropane C3H10N2 74.0844
3 HMDB00005 2-Ketobutyric acid C4H6O3 102.0317
4 HMDB00008 2-Hydroxybutyric acid C4H8O3 104.0473
5 HMDB00010 2-Methoxyestrone C19H24O3 300.1725
6 HMDB00011 (R)-3-Hydroxybutyric acid C4H8O3 104.0473
The final command i.e. hits <- database_query(geoRgeR = s2, adducts = negative, db = db) now works fine.
I am now getting the tables for s3 and hits (PFA below, sheet1 and 2 are from my runs while sheet3 is from your article).However, the information in these tables is incomplete. I would like to know how was the supplementary table in the manuscript (which has mzmed, rtmed, atoms etc. information) and  was generated using the sample data.

Thanks a lot,
Manohar

[geoRge output_sample data.xlsx](https://github.com/jcapelladesto/geoRge/files/1292433/geoRge.output_sample.data.xlsx)

**Comment by manohar8** [comment]
Hi Jordi,
Sorry by mistake I closed this comment. Your suggestion worked. Thank you very much. I just included one more line of code before hits command i.e

db<- read.csv(file="C:/Users/Admin/Documents/R/win-library/3.2/geoRge/extdata/ExampleDatabase.csv", header=TRUE, sep=",")
head(db)
HMDB.ID Name Chemical.Formula Monoisotopic.Mass
1 HMDB00001 1-Methylhistidine C7H11N3O2 169.0851
2 HMDB00002 1,3-Diaminopropane C3H10N2 74.0844
3 HMDB00005 2-Ketobutyric acid C4H6O3 102.0317
4 HMDB00008 2-Hydroxybutyric acid C4H8O3 104.0473
5 HMDB00010 2-Methoxyestrone C19H24O3 300.1725
6 HMDB00011 (R)-3-Hydroxybutyric acid C4H8O3 104.0473
The final command i.e. hits <- database_query(geoRgeR = s2, adducts = negative, db = db) now works fine.
I am now getting the tables for s3 and hits (PFA below, sheet1 and 2 are from my runs while sheet3 is from your article).However, the information in these tables is incomplete. I would like to know how was the supplementary table in the manuscript (which has mzmed, rtmed, atoms etc. information) and was generated using the sample data.

Thanks a lot,
Manohar

geoRge output_sample data.xlsx

**Comment by jcapelladesto** [comment]
Now I understand what happened before, it depends on the regional setting for comma separated values, i guess your OS expects ";" instead of ",". It is great that you sorted that out.

To generate a table like the XLSX one, you just need to use the` cbind` function, it is a base function from R, it attaches data.frames colum-wise, but they must have the same number of rows. Just select the data.frame object that you want to attach and use the function like this:  `cbind(df1,df2)`

**Comment by manohar8** [comment]
Thanks Jordi for letting me know this. cbind has combined s3 and hits tables.
Sorry if I have not been clear in the last comment, but the issue is  I am not able to see data for columns with headings highlighted in yellow (please see attached file below). Are there any more lines of code which needs to be included for getting yellow heading columns?
Please let me know. Once I am able to run this sample data then I can test labeled dataset from my lab.
[geoRge output_sample data1.xlsx](https://github.com/jcapelladesto/geoRge/files/1295455/geoRge.output_sample.data1.xlsx)

**Comment by jcapelladesto** [comment]
The data that you are looking for is the dataframe located at `s2$geoRge`.

**Comment by manohar8** [comment]
Thank you very much Jordi. I have the complete data from geoRge now. You have been very patient during all this time.

I have now tried running geoRge for lab data. First I started with xcms for .mzxml files (2 labeled and 2 unlabeled samples, example sample name- C12_IITB1_1)
xcms code is as below
xset <- xcmsSet(method="centWave", ppm=50, peakwidth=c(10,60))
classes = c(rep("C12_IITB1",2),rep("C13_IITB1",2))
xset2 <- retcor(xset,method="obiwarp", profStep=0.1)
xset3 <- group(xset2, mzwid=0.0025, minfrac=0.5, bw=5)
xset3 <- fillPeaks(xset3) 
data_IITB1 <- xset3

Load geoRge package
library(geoRge)
data_IITB1 
s1 <- PuInc_seeker(xcmsSet=data_IITB1,ULtag="C12_IITB1",Ltag="C13_IITB1",sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 1000)
Error in PuInc_seeker(xcmsSet = data_IITB1, ULtag = "C12_IITB1", Ltag = "C13_IITB1",  : 
  unused argument (xcmsSet = data_IITB1)

Can you please let me know why this is happening? Is it because of xcms dataset? Please reply.

Thanks,
Manohar

**Comment by jcapelladesto** [comment]
Please, pay attention to the argument names. 

"xcmsSet" is the class of the object. But in geoRge, the first argument of PuInc_seeker is "XCMSet".
The error indicates: unused argument (xcmsSet = data_IITB1). Meaning that this function does not know how to use xcmsSet, because it is not supposed to be there.

Tip: Look at the example and copy the arguments, then fill them with values according to your data. Or press "TAB" key to see all the arguments of any function.

**Comment by manohar8** [comment]
Thanks. I have now tried replacing xcmsSet with XCMSet in s1
 s1 <- PuInc_seeker(XCMSet=data_IITB1,ULtag="C12_IITB1",Ltag="C13_IITB1",sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 1000)

Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  'data' must be of a vector type, was 'NULL'

This is the second issue. For all the commands in xcms workflow I have edited the parameters according to our settings. The only command which I did not use was sampclass(xset) <- substring(sampnames(xset), 1, 21). Instead of this I used classes = c(rep("C12_IITB1",2),rep("C13_IITB1",2)). 

Are these two issues linked? How to go beyond this stage? 

Manohar

**Comment by jcapelladesto** [comment]
I think I have an idea of what is causing this. Please show me the output of running this code:
```
data_IITB1
data_IITB1@phenoData
```

**Comment by manohar8** [comment]
data_IITB1@phenoData       

class
C12_IITB1_1   C12
C12_IITB1_2   C12
C13_IITB1_1   C13
C13_IITB1_2   C13

**Comment by jcapelladesto** [comment]
Ok. This is what is causing the problem. The second column should match the pattern of the sample names but without the last "_X".
So yes, it has to do with not modifiying the sampclass of your dataset as you mentioned in the last post.
Try this 
`sampclass(data_IITB1) <- c(rep("C12_IITB1",2),rep("C13_IITB1",2))`
and then run PuInc_seeker again

**Comment by manohar8** [comment]
Brilliant!!!
All works fine now.  Although at this moment very few metabolites are showing labeling but I will edit the parameters and look for improvement.

I have read from the previous post that geoRge performs better as compared to X13CMS when it comes to false positives. I think that is a major plus point. 

Thank you for your suggestions throughout these comments. It was immensely helpful for me!

Cheers,
Manohar

**Comment by jcapelladesto** [comment]
Since geoRge relies on the statistics of a T-test, it has the same drawbacks (limitations):

-  Depends on the N (number of files in this case). The higher the N the easier it will be to see if there is differences (more positives, probably less false positives too)
- Depends on the homogeneity of the population. Meaning that if samples are not "homogenous", similar between them, it will be harder to find differences despite the N.

Seeing that you have only 2 vs 2 files (which is the actual minimum for geoRge to work), you could be more flexible in terms of p.value trheshold in PuInc_seeker (which will increase the positives) and be more strict in terms of intensity for basepeak_finder (normally metabolite compounds have a high intensity in the base peak).

When looking at the results, if the name of the hit is interesting and the number of labelled compounds matches with what is "biologically expected", even if it is low intensity, it would probably a good hit. I would recommend double check that looking at the raw data in the instrument, when labelling occurs the pattern is easy to distinguish.

Good luck 

I will leave this issue open for a couple of weeks just in case you need to ask something again.

**Comment by manohar8** [comment]
Hi Jordi, geoRge is working well and we are able to see the isotopic differences in our samples. Thank you very much for all the support.  I am closing this issue now.

Manohar
