### ISSUE TITLE
I don't known what's wrong?

### ISSUE THREAD

**Issue by minyan90** [jcapelladesto/geoRge#6]

**Comment by jcapelladesto** [comment]
Dear minyan90,

Thank you very much for testing geoRge.
Looking at your error, I think that you do not have XCMS package installed.
Use the following code to do it:

source("https://bioconductor.org/biocLite.R")
biocLite("xcms")

geoRge needs to run on an xcmSet that it is created using  XCMS R package,
if you do not know what parameters to use check XCMS-Online or metabolomics
forums.

If you encounter any other problems, do not hesistate to contact me.

Yours,

Jordi

2016-03-09 2:13 GMT+01:00 minyan90 notifications@github.com:
