### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DoYup** [jcapelladesto/geoRge#7]
Dear

I was simply following it but it was returned with the error message following the script

s1 <- PuInc_seeker(XCMSet=xset3,ULtag="CELL_Glc12",Ltag="CELL_Glc13",sep.pos="f")

Error in if (sep.pos.front) { : argument is not interpretable as logical

Would you help me figure it out? thanks

**Comment by jcapelladesto** [comment]
Dear DoYup,

Thank you for pointing this out. It seems you checked the vignette, but it needs to be updated since the arguments of the functions have been changed:

To test the data from the package you need to run the following:

```
s1 <- PuInc_seeker(XCMSet=mtbls213,ULtag="CELL_Glc12",Ltag="CELL_Glc13",
sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 4000)

s2 <- basepeak_finder(PuIncR = s1, XCMSet = mtbls213, UL.atomM=12.0,L.atomM=13.003355,
	ppm.s=6.5,Basepeak.minInt=2000)
```
This should work. If you encounter any other error, please answer in this issue.

Thank you again. 

Jordi

**Comment by DoYup** [comment]
Awesome! Thank you very much.

But unfortunately, it returned with another error "Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent"

Here is what I wrote in R,

> install.packages("devtools", dependencies=TRUE)
> library(devtools) 

> install_github("jcapelladesto/geoRge")
> library(geoRge) 

> data(mtbls213)

s1 <- PuInc_seeker(XCMSet=mtbls213,ULtag="CELL_Glc12",Ltag="CELL_Glc13",
sep.pos.front=TRUE ,fc.threshold=1.5,p.value.threshold=.05,PuInc.int.lim = 4000)

**Comment by jcapelladesto** [comment]
I am really sorry for this.

It seems I made a mistake in the last commit. I will try to correct it ASAP. 
The package should be working correctly by tomorrow.

Thank you again and sorry.

**Comment by DoYup** [comment]
Thanks

I am going to have 13C experiment results soon. I would love to use the Package for the publication.
Thank you again.

**Comment by vivekmishra8739** [comment]
Hi there!

I am unable to use geoRge. Please provide me the steps following which I can use geoRge. I tried muliple times but failed everytime. Please help.

**Comment by jcapelladesto** [comment]
@vivekmishra8739  Please **create a new Issue** for your questions, I need you to show me what you have tried to do and what messages you got when the package failed (copy and paste them in your Issue). Also, make sure you have the latest version of geoRge and try to run the example as in [here](https://github.com/jcapelladesto/geoRge/blob/master/README.md)
